local  gradeInfo = 
{
	{ lscore = 0	,	male = "布衣", famale = "民女" },
	{ lscore = 10	,	male = "里胥", famale = "里胥夫人" },
	{ lscore = 15	,	male = "里正", famale = "里正夫人" },
	{ lscore = 25	,	male = "县令", famale = "县令夫人" },
	{ lscore = 45	,	male = "知府", famale ="知府夫人" },
	{ lscore = 70	,	male = "从事", famale = "从事夫人" },
	{ lscore = 100	,	male = "提辖", famale = "提辖夫人" },
	{ lscore = 135	,	male = "教头", famale = "教头夫人" },
	{ lscore = 175	,	male = "校尉", famale = "校尉夫人" },
	{ lscore = 225	,	male = "抚军", famale = "抚军夫人" },
	{ lscore = 500	,	male = "巡抚", famale = "巡抚夫人" },
	{ lscore = 600	,	male = "都督", famale = "都督夫人" },
	{ lscore = 700	,	male = "太守", famale = "太守夫人" },
	{ lscore = 800	,	male = "刺史", famale = "资明夫人" },
	{ lscore = 900	,	male = "经略使", famale = "钦圣夫人" },
	{ lscore = 1000	,	male = "节度使", famale = "尚寝夫人" },
	{ lscore = 1100	,	male = "司马", famale = "尚服夫人" },
	{ lscore = 1200	,	male = "囧卿", famale = "尚怡夫人" },
	{ lscore = 1300	,	male = "都尉", famale = "宝华夫人" },
	{ lscore = 1400	,	male = "尹", famale = "宫正夫人" },
	{ lscore = 1500	,	male = "令尹", famale = "尚宫夫人" },
	{ lscore = 1700	,	male = "参军", famale = "采女" },
	{ lscore = 1900	,	male = "郎中", famale = "御女" },
	{ lscore = 2100	,	male = "侍中", famale = "宝林" },
	{ lscore = 2300	,	male = "侍郎", famale = "人才" },
	{ lscore = 2500	,	male = "长史", famale = "美人" },
	{ lscore = 2700	,	male = "太史", famale = "婕妤" },
	{ lscore = 2900	,	male = "士大夫", famale = "充媛" },
	{ lscore = 3100	,	male = "大夫", famale = "充容" },
	{ lscore = 5000	,	male = "上大夫", famale = "昭仪" },
	{ lscore = 6000	,	male = "太尉", famale = "修媛" },
	{ lscore = 7000	,	male = "左徒", famale = "修容" },
	{ lscore = 8000	,	male = "枢密使", famale = "修仪" },
	{ lscore = 9000	,	male = "御史", famale = "昭媛" },
	{ lscore = 10000,	male = "军机章京", famale = "昭容" },
	{ lscore = 11000,	male = "军机大臣", famale = "县主" },
	{ lscore = 12000,	male = "参知政事", famale = "郡主" },
	{ lscore = 20000,	male = "大将军", famale = "公主" },
	{ lscore = 25000,	male = "上卿", famale = "贤妃" },
	{ lscore = 30000,	male = "学士", famale = "德妃" },
	{ lscore = 35000,	male = "尚书", famale = "淑妃" },
	{ lscore = 40000,	male = "少保", famale = "元妃" },
	{ lscore = 50000,	male = "太傅", famale = "贵妃" },
	{ lscore = 60000,	male = "太师", famale = "长公主" },
	{ lscore = 70000,	male = "丞相", famale = "大长公主" },
	{ lscore = 80000,	male = "亲王", famale = "王后" },
	{ lscore = 100000,	male = "帝王", famale = "女皇" },
}


return gradeInfo